### ISSUE TITLE
buttons do not work when I import them locally in nextjs

### ISSUE THREAD

**Issue by eraykeskinmac** [GhassenEljday/react-mobile-app-button#30]
`<GooglePlayButton url={APKUrl} theme="dark" />` When I import as in this example, nextjs gives an error like this, I think the reason is written in nextjs docs 

./node_modules/react-mobile-app-button/lib/components/Button/button.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/react-mobile-app-button/lib/components/Button/index.js

**Comment by lucaswiix** [comment]
same

**Comment by GhassenEljday** [comment]
Hey @eraykeskinmac 
Thank you so much for the detailed issue report, we'll start working on it so u can enjoy our library on Next.js

**Comment by GhassenEljday** [comment]
Hey Guys,

We've got a new version on the way, packed with all the fixes needed for this issue.

Thank you for reporting

**Comment by jack2684** [comment]
I got the same issue even when using latest version as of today.

```
"react-mobile-app-button": "^1.2.18",
```

<img width="1246" alt="image" src="https://github.com/GhassenEljday/react-mobile-app-button/assets/1225301/37ba0dd4-c8d7-4a65-9438-45024d23cfd6">

**Comment by xiCO2k** [comment]
Same here, thanks for the package.

**Comment by GhassenEljday** [comment]
Issue Fiex #45 

version 1.2.19 is now available
