### ISSUE TITLE
Google Play button does not display correctly on iPhone 12,13,14 Pro Max

### ISSUE THREAD

**Issue by platonicvizard** [GhassenEljday/react-mobile-app-button#36]
The text on the Google Play button appears stacked on top of each other.

<img width="387" alt="image" src="https://github.com/GhassenEljday/react-mobile-app-button/assets/10996881/56477a15-07e9-4897-97ea-72c40cb66127">

**Comment by GhassenEljday** [comment]
Hello, @platonicvizard
I appreciate your report. The button's width and height can still be changed.

To avoid this kind of problem, we might include a `textSize` prop in the future.
