### ISSUE TITLE
Play Store badge should read "Get it on Google Play"

### ISSUE THREAD

**Issue by cronchie** [GhassenEljday/react-mobile-app-button#4]
The Play Store badge should read "Get it on Google Play":

https://play.google.com/intl/en_us/badges/

as of right now, it says "Get in on Google Play":

<img width="487" alt="image" src="https://user-images.githubusercontent.com/6097369/235521243-abf43ea3-c8b6-47a7-9f8f-ad7ae5753c06.png">

**Comment by GhassenEljday** [comment]
Thank You for the PR, I already merged it 🤝 ❤️
